from __future__ import annotations

import pandas as pd
import streamlit as st

from utils.app_state import require_data
from utils.charts import current_vs_target_radar, scenario_target_bar, theta_by_scenario
from utils.formatting import apply_global_style, scenario_label
from utils.load_data import SCENARIO_LABELS
from utils.optimizer import check_live_optimizer_available, normalise_weights, run_live_molp
from utils.transforms import build_improvement_table, build_scenario_table

st.set_page_config(page_title="Scenario Simulator", page_icon="⚙️", layout="wide")
apply_global_style()

app_data = require_data()
master_df = app_data["master"]
outputs = app_data["outputs"]
targets_df = outputs.get("molp_targets", pd.DataFrame())
payoff_df = outputs.get("molp_payoff_table", pd.DataFrame())
peer_weights_df = outputs.get("molp_peer_weights", pd.DataFrame())

st.sidebar.header("Scenario controls")
include_efficient = st.sidebar.checkbox("Include CCR-efficient benchmark suppliers", value=False)
supplier_pool = master_df.copy()
if not include_efficient and "ccr_efficiency" in supplier_pool.columns:
    supplier_pool = supplier_pool[pd.to_numeric(supplier_pool["ccr_efficiency"], errors="coerce") < 0.999]
if supplier_pool.empty:
    supplier_pool = master_df.copy()
suppliers = sorted(supplier_pool["supplier"].dropna().astype(str).unique().tolist())
supplier = st.sidebar.selectbox("Supplier", suppliers)
current_supplier = master_df[master_df["supplier"] == supplier].iloc[0]
is_ccr_efficient = pd.notna(current_supplier.get("ccr_efficiency")) and float(current_supplier.get("ccr_efficiency")) >= 0.999
live_available, live_message = check_live_optimizer_available()
mode_options = ["Precomputed scenarios"]
if live_available:
    mode_options.append("Live custom optimiser")
mode = st.sidebar.radio("Scenario mode", mode_options, help="Live custom optimiser requires Gurobi and the local risk_supplier_improvement package.")

if mode == "Precomputed scenarios":
    scenario_label_selected = st.sidebar.selectbox("Precomputed scenario", list(SCENARIO_LABELS.keys()))
    scenario = SCENARIO_LABELS[scenario_label_selected]
else:
    scenario = "custom_live"
    st.sidebar.caption("Set criterion weights. They will be normalised to sum to 1 before solving.")
    w_price = st.sidebar.slider("Price weight", 0.0, 1.0, 0.20, 0.05)
    w_late = st.sidebar.slider("Late delivery weight", 0.0, 1.0, 0.20, 0.05)
    w_error = st.sidebar.slider("Shipping error weight", 0.0, 1.0, 0.20, 0.05)
    w_lead = st.sidebar.slider("Lead time weight", 0.0, 1.0, 0.20, 0.05)
    w_quality = st.sidebar.slider("Product quality weight", 0.0, 1.0, 0.20, 0.05)
    run_button = st.sidebar.button("Run live MOLP", type="primary")

st.title("3. Scenario Simulator")
if live_available:
    st.success(live_message)
else:
    st.info("Live custom MOLP unavailable in this environment. Using precomputed scenario outputs.")
    st.caption(live_message)

st.markdown(
    """
    <div class="muted-box">
    <b>Scenario meanings:</b>
    <span class="badge badge-blue">Balanced</span> neutral compromise baseline
    <span class="badge badge-grey">Cost-led</span> emphasises unit-price improvement
    <span class="badge badge-amber">Delivery-led</span> emphasises late delivery, errors, and lead time
    <span class="badge badge-green">Quality-led</span> emphasises product-quality gain.
    </div>
    """,
    unsafe_allow_html=True,
)

if mode == "Precomputed scenarios":
    st.markdown(
        f"""
        <div class="guide-box">
        <strong>Precomputed mode.</strong> You are comparing the four scenario outputs already generated by the modelling pipeline. Selected view: <b>{scenario_label(scenario)}</b> for Supplier <b>{supplier}</b>.
        Sidebar scenario changes filter stored MOLP outputs; it does not re-solve MCDA, DEA, or MOLP.
        </div>
        """,
        unsafe_allow_html=True,
    )
    left, right = st.columns([1.2, 0.8], gap="large")
    with left:
        st.subheader("Target metrics across scenarios")
        scenario_table = build_scenario_table(targets_df, supplier)
        st.dataframe(scenario_table, width="stretch", hide_index=True)
    with right:
        st.subheader("Theta by scenario")
        st.plotly_chart(theta_by_scenario(targets_df, supplier), width="stretch")

    chart_col, table_col = st.columns([1.1, 1.0], gap="large")
    with chart_col:
        st.subheader("Selected scenario target")
        if is_ccr_efficient:
            st.markdown(
                """
                <div class="muted-box">
                <b>This supplier is already CCR-efficient; no development target is required.</b>
                Use this supplier as a benchmark/monitoring case. DEA efficiency is an operational frontier diagnosis, not an overall desirability claim.
                </div>
                """,
                unsafe_allow_html=True,
            )
        else:
            target_chart = scenario_target_bar(master_df, targets_df, supplier, scenario)
            if target_chart is None:
                st.info("No selected-scenario target chart can be drawn because current-target data is unavailable.")
            else:
                st.plotly_chart(target_chart, width="stretch")
    with table_col:
        st.subheader("Performance comparison")
        improvement = build_improvement_table(master_df, targets_df, supplier, scenario)
        if is_ccr_efficient:
            st.info("CCR-efficient suppliers are monitoring/benchmark cases here; they do not require the same target-improvement panel as development candidates.")
        elif improvement.empty:
            st.info("No improvement table available.")
        else:
            display = improvement.copy()
            display["Improvement %"] = display["Improvement %"].map(lambda x: "—" if pd.isna(x) else f"{x:.1f}%")
            display["Normalised room"] = display["Normalised room"].map(lambda x: "—" if pd.isna(x) else f"{x:.1f}")
            st.dataframe(display, width="stretch", hide_index=True)

    st.subheader("Managerial interpretation")
    st.markdown(
        """
        <div class="decision-box">
        Use this page to check whether the recommended target changes materially when management prioritises cost, delivery reliability, or product quality. Large target movement across scenarios indicates that the recommendation is preference-sensitive and should be reported with caution.
        </div>
        """,
        unsafe_allow_html=True,
    )
    with st.expander("Show payoff table for selected supplier/scenario"):
        if payoff_df.empty:
            st.info("No payoff table available.")
        else:
            filtered = payoff_df[(payoff_df["supplier"] == supplier) & (payoff_df["scenario"] == scenario)]
            st.dataframe(filtered, width="stretch", hide_index=True)

else:
    weights = normalise_weights({"price": w_price, "late": w_late, "error": w_error, "lead": w_lead, "quality": w_quality})
    st.markdown(
        f"""
        <div class="warning-box">
        <strong>Live custom mode.</strong> This mode calls the original <code>risk_supplier_improvement</code> optimiser. It needs <b>polars</b>, <b>gurobipy</b>, and a valid <b>Gurobi licence</b>. If this is a live class demo, keep precomputed mode as the safe default.
        Slider weights are normalised to sum to 1 before solving.
        </div>
        """,
        unsafe_allow_html=True,
    )
    wcols = st.columns(5)
    for col, label, key in zip(wcols, ["Price", "Late", "Error", "Lead", "Quality"], ["price", "late", "error", "lead", "quality"]):
        col.metric(label, f"{weights[key]:.2f}")

    if not run_button:
        st.info("Set weights in the sidebar and click **Run live MOLP**.")
    else:
        with st.spinner("Running live post-DEA MOLP..."):
            dea_df = outputs.get("dea_team_ccr_efficiency", pd.DataFrame())
            if dea_df.empty:
                dea_df = app_data["inputs"].get("dea_efficiency", pd.DataFrame())
            result = run_live_molp(
                molp_inputs_df=outputs.get("supplier_molp_inputs", pd.DataFrame()),
                dea_df=dea_df,
                supplier=supplier,
                weights=weights,
            )
        if not result.ok:
            st.error(result.message)
        else:
            st.success(result.message)
            live_targets = result.targets
            live_peers = result.peers
            left, right = st.columns([1.05, 0.95], gap="large")
            with left:
                st.subheader("Live current vs target radar")
                live_radar = current_vs_target_radar(master_df, live_targets, supplier, "custom_live")
                if live_radar is None:
                    st.info("No live radar chart can be drawn because current-target data is unavailable.")
                else:
                    st.plotly_chart(live_radar, width="stretch")
            with right:
                st.subheader("Live target table")
                st.dataframe(live_targets, width="stretch", hide_index=True)
                st.subheader("Live peer weights")
                st.dataframe(live_peers, width="stretch", hide_index=True)
            with st.expander("Live payoff table"):
                st.dataframe(result.payoff, width="stretch", hide_index=True)
